# Generated by Django 3.2.3 on 2021-07-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30)),
                ('frase', models.CharField(max_length=30)),
                ('entrenador', models.CharField(max_length=30)),
                ('cantidadJugador', models.IntegerField()),
                ('estado_Equipo', models.CharField(choices=[('activo', 'activo'), ('eliminado', 'eliminado')], default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=15)),
                ('contra', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30)),
                ('numeroEquipo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=10)),
                ('fechaInicio', models.CharField(max_length=10)),
                ('fechaFin', models.CharField(max_length=10)),
                ('tipo_Tor', models.CharField(choices=[('eliminatoria', 'eliminatoria'), ('corriente', 'corriente')], default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=10)),
                ('estado_Ticket', models.CharField(choices=[('espera', 'espera'), ('comprado', 'comprado')], default='', max_length=30)),
                ('PropiedadTorneo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APPadministracion.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10)),
                ('posicion_Jugador', models.CharField(choices=[('mediocampista', 'mediocampista'), ('defensa', 'defensa'), ('portero', 'portero'), ('delantero', 'delantero')], default='', max_length=30)),
                ('PropiedadEquipo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APPadministracion.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Implementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(max_length=50)),
                ('tipo_Im', models.CharField(choices=[('donado', 'donado'), ('comprado', 'comprado')], default='', max_length=30)),
                ('PropiedadTorneo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APPadministracion.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='PropiedadTorneo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APPadministracion.torneo'),
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10)),
                ('PropiedadTorneo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APPadministracion.torneo')),
            ],
        ),
    ]
