# Generated by Django 3.2.3 on 2021-08-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPadministracion', '0002_encuentro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
